#!/bin/bash

echo "Fixing RIL headers for a5ltechn..."

# Add definitions to ril.h
RIL_H="hardware/ril/include/telephony/ril.h"

if grep -q "RIL_OEM_REQUEST_BASE" $RIL_H; then
    echo "RIL definitions already exist"
else
    echo "Adding RIL definitions..."
    cat >> $RIL_H << 'EOF'

/* Samsung OEM RIL extensions */
#define RIL_OEM_REQUEST_BASE 10000
#define RIL_REQUEST_GET_CELL_BROADCAST_CONFIG (RIL_OEM_REQUEST_BASE + 0)
#define RIL_REQUEST_SEND_ENCODED_USSD (RIL_OEM_REQUEST_BASE + 1)
#define RIL_REQUEST_SET_PDA_MEMORY_STATUS (RIL_OEM_REQUEST_BASE + 2)
#define RIL_REQUEST_GET_PHONEBOOK_STORAGE_INFO (RIL_OEM_REQUEST_BASE + 3)
#define RIL_REQUEST_GET_PHONEBOOK_ENTRY (RIL_OEM_REQUEST_BASE + 4)
#define RIL_REQUEST_ACCESS_PHONEBOOK_ENTRY (RIL_OEM_REQUEST_BASE + 5)
#define RIL_REQUEST_DIAL_VIDEO_CALL (RIL_OEM_REQUEST_BASE + 6)
#define RIL_REQUEST_CALL_DEFLECTION (RIL_OEM_REQUEST_BASE + 7)
#define RIL_REQUEST_READ_SMS_FROM_SIM (RIL_OEM_REQUEST_BASE + 8)
#define RIL_REQUEST_USIM_PB_CAPA (RIL_OEM_REQUEST_BASE + 9)
#define RIL_REQUEST_LOCK_INFO (RIL_OEM_REQUEST_BASE + 10)
#define RIL_REQUEST_DIAL_EMERGENCY (RIL_OEM_REQUEST_BASE + 11)
#define RIL_REQUEST_GET_STOREAD_MSG_COUNT (RIL_OEM_REQUEST_BASE + 12)
#define RIL_REQUEST_STK_SIM_INIT_EVENT (RIL_OEM_REQUEST_BASE + 13)
#define RIL_REQUEST_GET_LINE_ID (RIL_OEM_REQUEST_BASE + 14)
#define RIL_REQUEST_SET_LINE_ID (RIL_OEM_REQUEST_BASE + 15)
#define RIL_REQUEST_GET_SERIAL_NUMBER (RIL_OEM_REQUEST_BASE + 16)
#define RIL_REQUEST_GET_MANUFACTURE_DATE_NUMBER (RIL_OEM_REQUEST_BASE + 17)
EOF
fi

# Clean intermediates
rm -rf out/target/product/a5ltechn/obj/SHARED_LIBRARIES/libril_intermediates/

echo "Done. Re-run brunch a5ltechn"
